location2idx = {
    'move': 0,
    'turnLeft': 1,
    'turnRight': 2,
    'pickMarker': 3,
    'putMarker': 4,
    'while:frontIsClear': 5,
    'while:leftIsClear': 6,
    'while:rightIsClear': 7,
    'while:markersPresent': 8,
    'while:notFrontIsClear': 9,
    'while:notLeftIsClear': 10,
    'while:notRightIsClear': 11,
    'while:noMarkersPresent': 12,
    'repeatUntil:boolGoal': 13,
    'repeat:1': 14,
    'repeat:2': 15,
    'repeat:3': 16,
    'repeat:4': 17,
    'repeat:5': 18,
    'repeat:6': 19,
    'repeat:7': 20,
    'repeat:8': 21,
    'repeat:9': 22,
    'repeat:10': 23,
    'if:frontIsClear': 24,
    'if:leftIsClear': 25,
    'if:rightIsClear': 26,
    'if:markersPresent': 27,
    'if:notFrontIsClear': 28,
    'if:notLeftIsClear': 29,
    'if:notRightIsClear': 30,
    'if:noMarkersPresent': 31,
    'ifElse:frontIsClear': 32,
    'ifElse:leftIsClear': 33,
    'ifElse:rightIsClear': 34,
    'ifElse:markersPresent': 35,
    'ifElse:notFrontIsClear': 36,
    'ifElse:notLeftIsClear': 37,
    'ifElse:notRightIsClear': 38,
    'ifElse:noMarkersPresent': 39,
}

idx2location = {v: k for k, v in location2idx.items()}

decision2idx = {
    'binary:0': 0,
    'binary:1': 1,
    'dir:1': 2,
    'dir:2': 3,
    'dir:3': 4,
    'dir:4': 5,
    'pos:0': 6,
    'pos:1': 7,
    'pos:2': 8,
    'pos:3': 9,
    'pos:4': 10,
}

idx2decision = {v: k for k, v in decision2idx.items()}
